const admin = require('firebase-admin');
const { google } = require('googleapis');
const { onDocumentWritten } = require('firebase-functions/v2/firestore');
const logger = require('firebase-functions/logger');

admin.initializeApp();

const db = admin.firestore();
const driveAuth = new google.auth.GoogleAuth({
  scopes: ['https://www.googleapis.com/auth/drive.readonly'],
});

exports.syncSeriesFromDriveFolder = onDocumentWritten(
  {
    document: 'series/{seriesId}',
    region: 'us-central1',
  },
  async (event) => {
    const afterSnapshot = event.data.after;
    if (!afterSnapshot.exists) {
      return;
    }

    const beforeData = event.data.before.exists ? event.data.before.data() : null;
    const afterData = afterSnapshot.data();
    const driveFolderUrl = `${afterData.driveFolderUrl || ''}`.trim();

    const syncRequestedChanged =
      toMillis(beforeData?.syncRequestedAt) !== toMillis(afterData.syncRequestedAt);
    const folderChanged =
      `${beforeData?.driveFolderUrl || ''}`.trim() !== driveFolderUrl;

    if (!syncRequestedChanged && !folderChanged) {
      return;
    }

    const folderId = extractFolderId(driveFolderUrl);
    if (!folderId) {
      await afterSnapshot.ref.set(
        {
          syncStatus: 'error',
          syncError: 'Nao foi possivel extrair o folderId do link do Google Drive.',
          updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        },
        { merge: true },
      );
      return;
    }

    await afterSnapshot.ref.set(
      {
        folderId,
        syncStatus: 'syncing',
        syncError: admin.firestore.FieldValue.delete(),
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      },
      { merge: true },
    );

    try {
      const folderResourceKey = extractResourceKey(driveFolderUrl);
      const files = await listFolderFiles(folderId, folderResourceKey);
      const videoFiles = files.filter((file) => `${file.mimeType || ''}`.startsWith('video/'));

      const sortedFiles = [...videoFiles].sort((a, b) =>
        a.name.localeCompare(b.name, undefined, { numeric: true, sensitivity: 'base' }),
      );

      const videosRef = afterSnapshot.ref.collection('videos');
      const existingSnapshot = await videosRef.get();
      const existingById = new Map(existingSnapshot.docs.map((doc) => [doc.id, doc.data()]));

      const batch = db.batch();
      const syncedIds = new Set();

      sortedFiles.forEach((file, index) => {
        const docRef = videosRef.doc(file.id);
        const existing = existingById.get(file.id) || {};
        const generatedThumbnail = buildThumbnailUrl(file);
        const rawTitle = stripExtension(file.name);
        const autoGeneratedTitle = sanitizeEpisodeTitle(rawTitle);
        const payload = {
          driveFileId: file.id,
          driveFileUrl: buildDriveFileUrl(file.id, file.resourceKey),
          episodeNumber: inferEpisodeNumber(file.name, index),
          sourceName: file.name,
          autoGeneratedTitle,
          autoThumbnailUrl: generatedThumbnail,
          mimeType: file.mimeType || '',
          syncedAt: admin.firestore.FieldValue.serverTimestamp(),
          updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        };

        if (shouldRefreshAutoTitle(existing, rawTitle)) {
          payload.title = autoGeneratedTitle;
        }

        if (!`${existing.description || ''}`.trim()) {
          payload.description = '';
        }

        if (!`${existing.thumbnailUrl || ''}`.trim() && generatedThumbnail) {
          payload.thumbnailUrl = generatedThumbnail;
        }

        if (!existing.createdAt) {
          payload.createdAt = admin.firestore.FieldValue.serverTimestamp();
        }

        batch.set(docRef, payload, { merge: true });
        syncedIds.add(file.id);
      });

      existingSnapshot.docs.forEach((doc) => {
        if (!syncedIds.has(doc.id)) {
          batch.delete(doc.ref);
        }
      });

      const firstThumbnail = sortedFiles.length > 0 ? buildThumbnailUrl(sortedFiles[0]) : '';
      const seriesUpdate = {
        folderId,
        syncStatus: 'ready',
        syncError: admin.firestore.FieldValue.delete(),
        lastSyncedAt: admin.firestore.FieldValue.serverTimestamp(),
        videoCount: sortedFiles.length,
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      };

      if (!`${afterData.thumbnailUrl || ''}`.trim() && firstThumbnail) {
        seriesUpdate.thumbnailUrl = firstThumbnail;
      }

      batch.set(afterSnapshot.ref, seriesUpdate, { merge: true });
      await batch.commit();

      logger.info('Series synchronized from Drive folder.', {
        seriesId: event.params.seriesId,
        folderId,
        videoCount: sortedFiles.length,
      });
    } catch (error) {
      logger.error('Failed to synchronize Drive folder.', error);
      await afterSnapshot.ref.set(
        {
          syncStatus: 'error',
          syncError: error instanceof Error ? error.message : String(error),
          updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        },
        { merge: true },
      );
    }
  },
);

function toMillis(value) {
  if (!value || typeof value.toMillis !== 'function') {
    return null;
  }
  return value.toMillis();
}

function extractFolderId(link) {
  const direct = link.match(/\/folders\/([a-zA-Z0-9_-]+)/);
  if (direct) {
    return direct[1];
  }

  const query = link.match(/[?&]id=([a-zA-Z0-9_-]+)/);
  if (query) {
    return query[1];
  }

  return null;
}

function extractResourceKey(link) {
  const match = link.match(/[?&]resourcekey=([^&#]+)/i);
  return match ? decodeURIComponent(match[1]) : '';
}

async function listFolderFiles(folderId, folderResourceKey) {
  const client = await driveAuth.getClient();
  const tokenResponse = await client.getAccessToken();
  const accessToken =
    typeof tokenResponse === 'string' ? tokenResponse : tokenResponse?.token;

  if (!accessToken) {
    throw new Error('Nao foi possivel obter access token da service account.');
  }

  const files = [];
  let nextPageToken = '';

  do {
    const params = new URLSearchParams({
      q: `'${folderId}' in parents and trashed = false`,
      fields: 'nextPageToken,files(id,name,mimeType,thumbnailLink,resourceKey)',
      pageSize: '1000',
      orderBy: 'name_natural',
      supportsAllDrives: 'true',
      includeItemsFromAllDrives: 'true',
    });

    if (nextPageToken) {
      params.set('pageToken', nextPageToken);
    }

    const headers = {
      Authorization: `Bearer ${accessToken}`,
    };

    if (folderResourceKey) {
      headers['X-Goog-Drive-Resource-Keys'] = `${folderId}/${folderResourceKey}`;
    }

    const response = await fetch(`https://www.googleapis.com/drive/v3/files?${params}`, {
      headers,
    });

    if (!response.ok) {
      const body = await response.text();
      throw new Error(`Drive API returned ${response.status}: ${body}`);
    }

    const json = await response.json();
    files.push(...(json.files || []));
    nextPageToken = json.nextPageToken || '';
  } while (nextPageToken);

  return files;
}

function buildDriveFileUrl(fileId, resourceKey) {
  if (resourceKey) {
    return `https://drive.google.com/file/d/${fileId}/view?resourcekey=${encodeURIComponent(resourceKey)}`;
  }

  return `https://drive.google.com/file/d/${fileId}/view`;
}

function buildThumbnailUrl(file) {
  if (file.thumbnailLink) {
    return file.thumbnailLink;
  }

  if (!file.id) {
    return '';
  }

  return `https://drive.google.com/thumbnail?id=${file.id}&sz=w1000`;
}

function stripExtension(name) {
  return name.replace(/\.[^.]+$/, '');
}

function sanitizeEpisodeTitle(name) {
  let value = ` ${name} `;

  const patterns = [
    /\[[^\]]+\]/g,
    /\([^\)]*\b(?:www|\.com|\.net|\.org|site|rip|x264|x265|h\.?264|h\.?265|hevc|webrip|web-dl|bluray|1080p|720p|480p)\b[^\)]*\)/gi,
    /\b(?:www\.)?[a-z0-9-]+\.(?:com|net|org|io|tv|me|info|co)\b/gi,
    /\b(?:via|from|by)\s+[a-z0-9._-]+\b/gi,
    /\b(?:telegram|t\.me|@[\w.]+)\b/gi,
    /\b(?:webrip|web-dl|bluray|brrip|dvdrip|x264|x265|h\.?264|h\.?265|hevc|aac|dublado|dual audio|legendado|1080p|720p|480p)\b/gi,
  ];

  for (const pattern of patterns) {
    value = value.replace(pattern, ' ');
  }

  value = value
    .replace(/[._]+/g, ' ')
    .replace(/\s+-\s+/g, ' ')
    .replace(/\s{2,}/g, ' ')
    .trim();

  return value || name;
}

function shouldRefreshAutoTitle(existing, rawTitle) {
  const currentTitle = `${existing.title || ''}`.trim();
  const previousAutoTitle = `${existing.autoGeneratedTitle || ''}`.trim();
  const previousSourceTitle = stripExtension(`${existing.sourceName || ''}`.trim());

  return (
    !currentTitle ||
    currentTitle === previousAutoTitle ||
    currentTitle === previousSourceTitle ||
    currentTitle === rawTitle
  );
}

function inferEpisodeNumber(name, index) {
  const normalized = stripExtension(name);
  const patterns = [
    /\bs\d{1,2}\s*e\s*0*(\d{1,4})\b/i,
    /\b(?:ep|episode|episodio|episódio|capitulo|capítulo)\s*0*(\d{1,4})\b/i,
    /(?:^|[^\d])0*(\d{1,4})(?:[^\d]|$)/,
  ];

  for (const pattern of patterns) {
    const match = normalized.match(pattern);
    if (match) {
      return Number(match[1]);
    }
  }

  return index + 1;
}
