const admin = require('firebase-admin');
const { google } = require('googleapis');
const { onDocumentWritten } = require('firebase-functions/v2/firestore');
const logger = require('firebase-functions/logger');
const { randomUUID } = require('node:crypto');

admin.initializeApp();

const db = admin.firestore();
const storage = admin.storage();
const driveAuth = new google.auth.GoogleAuth({
  scopes: ['https://www.googleapis.com/auth/drive.readonly'],
});

exports.syncSeriesFromDriveFolder = onDocumentWritten(
  {
    document: 'series/{seriesId}',
    region: 'us-central1',
  },
  async (event) => {
    const afterSnapshot = event.data.after;
    if (!afterSnapshot.exists) {
      return;
    }

    const beforeData = event.data.before.exists ? event.data.before.data() : null;
    const afterData = afterSnapshot.data();
    const driveFolderUrl = `${afterData.driveFolderUrl || ''}`.trim();

    const syncRequestedChanged =
      toMillis(beforeData?.syncRequestedAt) !== toMillis(afterData.syncRequestedAt);
    const folderChanged =
      `${beforeData?.driveFolderUrl || ''}`.trim() !== driveFolderUrl;

    if (!syncRequestedChanged && !folderChanged) {
      return;
    }

    const folderId = extractFolderId(driveFolderUrl);
    if (!folderId) {
      await afterSnapshot.ref.set(
        {
          syncStatus: 'error',
          syncError: 'Nao foi possivel extrair o folderId do link do Google Drive.',
          updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        },
        { merge: true },
      );
      return;
    }

    await afterSnapshot.ref.set(
      {
        folderId,
        syncStatus: 'syncing',
        syncError: admin.firestore.FieldValue.delete(),
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      },
      { merge: true },
    );

    try {
      const folderResourceKey = extractResourceKey(driveFolderUrl);
      const { files, accessToken } = await listFolderFiles(folderId, folderResourceKey);
      const videoFiles = files.filter((file) => `${file.mimeType || ''}`.startsWith('video/'));

      const sortedFiles = [...videoFiles].sort((a, b) =>
        a.name.localeCompare(b.name, undefined, { numeric: true, sensitivity: 'base' }),
      );

      const videosRef = afterSnapshot.ref.collection('videos');
      const existingSnapshot = await videosRef.get();
      const existingById = new Map(existingSnapshot.docs.map((doc) => [doc.id, doc.data()]));

      const batch = db.batch();
      const syncedIds = new Set();
      let firstGeneratedThumbnail = '';

      for (const [index, file] of sortedFiles.entries()) {
        const docRef = videosRef.doc(file.id);
        const existing = existingById.get(file.id) || {};
        const existingAutoThumbnail = `${existing.autoThumbnailUrl || ''}`.trim();
        const parsedEpisode = parseEpisodeMetadata(file.name, index);
        const generatedThumbnail = await ensureStoredThumbnail({
          seriesId: event.params.seriesId,
          file,
          accessToken,
          existingAutoThumbnail,
        });
        if (!firstGeneratedThumbnail && generatedThumbnail) {
          firstGeneratedThumbnail = generatedThumbnail;
        }
        const rawTitle = stripExtension(file.name);
        const autoGeneratedTitle = sanitizeEpisodeTitle(rawTitle);
        const payload = {
          driveFileId: file.id,
          driveFileUrl: buildDriveFileUrl(file.id, file.resourceKey),
          seasonNumber: parsedEpisode.seasonNumber,
          episodeNumber: parsedEpisode.episodeNumber,
          partNumber: parsedEpisode.partNumber,
          sortKey: parsedEpisode.sortKey,
          sourceName: file.name,
          autoGeneratedTitle,
          autoThumbnailUrl: generatedThumbnail,
          mimeType: file.mimeType || '',
          syncedAt: admin.firestore.FieldValue.serverTimestamp(),
          updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        };

        if (shouldRefreshAutoTitle(existing, rawTitle)) {
          payload.title = autoGeneratedTitle;
        }

        if (!`${existing.description || ''}`.trim()) {
          payload.description = '';
        }

        if (!`${existing.thumbnailUrl || ''}`.trim() && generatedThumbnail) {
          payload.thumbnailUrl = generatedThumbnail;
        }

        if (!existing.createdAt) {
          payload.createdAt = admin.firestore.FieldValue.serverTimestamp();
        }

        batch.set(docRef, payload, { merge: true });
        syncedIds.add(file.id);
      }

      existingSnapshot.docs.forEach((doc) => {
        if (!syncedIds.has(doc.id)) {
          batch.delete(doc.ref);
        }
      });

      const firstThumbnail = firstGeneratedThumbnail;
      const seriesUpdate = {
        folderId,
        syncStatus: 'ready',
        syncError: admin.firestore.FieldValue.delete(),
        lastSyncedAt: admin.firestore.FieldValue.serverTimestamp(),
        videoCount: sortedFiles.length,
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      };

      if (!`${afterData.thumbnailUrl || ''}`.trim() && firstThumbnail) {
        seriesUpdate.thumbnailUrl = firstThumbnail;
      }

      batch.set(afterSnapshot.ref, seriesUpdate, { merge: true });
      await batch.commit();

      logger.info('Series synchronized from Drive folder.', {
        seriesId: event.params.seriesId,
        folderId,
        videoCount: sortedFiles.length,
      });
    } catch (error) {
      logger.error('Failed to synchronize Drive folder.', error);
      await afterSnapshot.ref.set(
        {
          syncStatus: 'error',
          syncError: error instanceof Error ? error.message : String(error),
          updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        },
        { merge: true },
      );
    }
  },
);

function toMillis(value) {
  if (!value || typeof value.toMillis !== 'function') {
    return null;
  }
  return value.toMillis();
}

function extractFolderId(link) {
  const direct = link.match(/\/folders\/([a-zA-Z0-9_-]+)/);
  if (direct) {
    return direct[1];
  }

  const query = link.match(/[?&]id=([a-zA-Z0-9_-]+)/);
  if (query) {
    return query[1];
  }

  return null;
}

function extractResourceKey(link) {
  const match = link.match(/[?&]resourcekey=([^&#]+)/i);
  return match ? decodeURIComponent(match[1]) : '';
}

async function listFolderFiles(folderId, folderResourceKey) {
  const client = await driveAuth.getClient();
  const tokenResponse = await client.getAccessToken();
  const accessToken =
    typeof tokenResponse === 'string' ? tokenResponse : tokenResponse?.token;

  if (!accessToken) {
    throw new Error('Nao foi possivel obter access token da service account.');
  }

  const files = [];
  let nextPageToken = '';

  do {
    const params = new URLSearchParams({
      q: `'${folderId}' in parents and trashed = false`,
      fields: 'nextPageToken,files(id,name,mimeType,thumbnailLink,resourceKey)',
      pageSize: '1000',
      orderBy: 'name_natural',
      supportsAllDrives: 'true',
      includeItemsFromAllDrives: 'true',
    });

    if (nextPageToken) {
      params.set('pageToken', nextPageToken);
    }

    const headers = {
      Authorization: `Bearer ${accessToken}`,
    };

    if (folderResourceKey) {
      headers['X-Goog-Drive-Resource-Keys'] = `${folderId}/${folderResourceKey}`;
    }

    const response = await fetch(`https://www.googleapis.com/drive/v3/files?${params}`, {
      headers,
    });

    if (!response.ok) {
      const body = await response.text();
      throw new Error(`Drive API returned ${response.status}: ${body}`);
    }

    const json = await response.json();
    files.push(...(json.files || []));
    nextPageToken = json.nextPageToken || '';
  } while (nextPageToken);

  return { files, accessToken };
}

function buildDriveFileUrl(fileId, resourceKey) {
  if (resourceKey) {
    return `https://drive.google.com/file/d/${fileId}/view?resourcekey=${encodeURIComponent(resourceKey)}`;
  }

  return `https://drive.google.com/file/d/${fileId}/view`;
}

function buildThumbnailUrl(file) {
  if (file.thumbnailLink) {
    return file.thumbnailLink;
  }

  if (!file.id) {
    return '';
  }

  return `https://drive.google.com/thumbnail?id=${file.id}&sz=w1000`;
}

async function ensureStoredThumbnail({ seriesId, file, accessToken, existingAutoThumbnail }) {
  if (existingAutoThumbnail.includes('firebasestorage.googleapis.com')) {
    return existingAutoThumbnail;
  }

  const sourceUrl = buildThumbnailUrl(file);
  if (!sourceUrl) {
    return '';
  }

  const sourceHeaders = {
    Authorization: `Bearer ${accessToken}`,
  };

  if (file.resourceKey) {
    sourceHeaders['X-Goog-Drive-Resource-Keys'] = `${file.id}/${file.resourceKey}`;
  }

  const response = await fetch(sourceUrl, {
    headers: sourceHeaders,
  });

  if (!response.ok) {
    logger.warn('Thumbnail fetch failed.', {
      fileId: file.id,
      status: response.status,
    });
    return '';
  }

  const contentType = response.headers.get('content-type') || 'image/jpeg';
  const buffer = Buffer.from(await response.arrayBuffer());
  if (!buffer.length) {
    return '';
  }

  const extension = contentType.includes('png') ? 'png' : 'jpg';
  const bucket = storage.bucket();
  const objectPath = `thumbnails/series/${seriesId}/${file.id}.${extension}`;
  const token = randomUUID();

  await bucket.file(objectPath).save(buffer, {
    resumable: false,
    contentType,
    metadata: {
      cacheControl: 'public,max-age=3600',
      metadata: {
        firebaseStorageDownloadTokens: token,
      },
    },
  });

  return `https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/${encodeURIComponent(objectPath)}?alt=media&token=${token}`;
}

function stripExtension(name) {
  return name.replace(/\.[^.]+$/, '');
}

function sanitizeEpisodeTitle(name) {
  let value = ` ${name} `;

  const patterns = [
    /\[[^\]]+\]/g,
    /\([^\)]*\b(?:www|\.com|\.net|\.org|site|rip|x264|x265|h\.?264|h\.?265|hevc|webrip|web-dl|bluray|1080p|720p|480p)\b[^\)]*\)/gi,
    /\b(?:www\.)?[a-z0-9-]+\.(?:com|net|org|io|tv|me|info|co)\b/gi,
    /\b(?:via|from|by)\s+[a-z0-9._-]+\b/gi,
    /\b(?:telegram|t\.me|@[\w.]+)\b/gi,
   
    /\b(?:webrip|web-dl|bluray|brrip|dvdrip|x264|x265|h\.?264|h\.?265|hevc|aac|dublado|dual audio|legendado|1080p|720p|480p)\b/gi,
  ];

  for (const pattern of patterns) {
    value = value.replace(pattern, ' ');
  }

  value = value
    .replace(/[._]+/g, ' ')
    .replace(/\b(?:s|t)\s*\d{1,2}\s*(?:e|ep)\s*\d{1,4}\b/gi, ' ')
    .replace(/\b\d{1,2}\s*x\s*\d{1,4}\b/gi, ' ')
    .replace(/\b(?:ep|episode|episodio|episódio)\s*[-:]?\s*0*\d{1,4}\b/gi, ' ')
    .replace(/\s+-\s+/g, ' ')
    .replace(/\s+-\s*$/g, ' ')
    .replace(/^\s*-\s+/g, ' ')
    .replace(/\s{2,}/g, ' ')
    .trim();

  return value || name;
}

function shouldRefreshAutoTitle(existing, rawTitle) {
  const currentTitle = `${existing.title || ''}`.trim();
  const previousAutoTitle = `${existing.autoGeneratedTitle || ''}`.trim();
  const previousSourceTitle = stripExtension(`${existing.sourceName || ''}`.trim());

  return (
    !currentTitle ||
    currentTitle === previousAutoTitle ||
    currentTitle === previousSourceTitle ||
    currentTitle === rawTitle
  );
}

function inferEpisodeNumber(name, index) {
  return parseEpisodeMetadata(name, index).episodeNumber;
}

function parseEpisodeMetadata(name, index) {
  const normalized = stripExtension(name);
  let seasonNumber = 0;
  let episodeNumber = 0;
  let partNumber = 0;

  const seasonEpisodePatterns = [
    /\b(?:s|t)\s*0*(\d{1,2})\s*(?:e|ep)\s*0*(\d{1,4})\b/i,
    /\b0*(\d{1,2})\s*x\s*0*(\d{1,4})\b/i,
  ];

  for (const pattern of seasonEpisodePatterns) {
    const match = normalized.match(pattern);
    if (match) {
      seasonNumber = Number(match[1]);
      episodeNumber = Number(match[2]);
      break;
    }
  }

  if (!episodeNumber) {
    const episodeOnlyPatterns = [
      /\b(?:ep|episode|episodio|episódio|capitulo|capítulo)\s*[-:]?\s*0*(\d{1,4})\b/i,
      /(?:^|[^\d])0*(\d{1,4})(?:[^\d]|$)/,
    ];

    for (const pattern of episodeOnlyPatterns) {
      const match = normalized.match(pattern);
      if (match) {
        episodeNumber = Number(match[1]);
        break;
      }
    }
  }

  const partPatterns = [
    /\b(?:parte|part|pt)\s*[-:]?\s*0*(\d{1,3})\b/i,
    /\b0*(\d{1,3})\/\d{1,3}\b/i,
  ];

  for (const pattern of partPatterns) {
    const match = normalized.match(pattern);
    if (match) {
      partNumber = Number(match[1]);
      break;
    }
  }

  if (!episodeNumber) {
    episodeNumber = index + 1;
  }

  return {
    seasonNumber,
    episodeNumber,
    partNumber,
    sortKey: buildSortKey(seasonNumber, episodeNumber, partNumber, normalized),
  };
}

function buildSortKey(seasonNumber, episodeNumber, partNumber, name) {
  const normalizedName = sanitizeEpisodeTitle(name).toLowerCase();
  return [
    padSortNumber(seasonNumber),
    padSortNumber(episodeNumber),
    padSortNumber(partNumber),
    normalizedName,
  ].join('-');
}

function padSortNumber(value) {
  return String(Number(value) || 0).padStart(4, '0');
}
